name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Train Rasa Model
      run: rasa train

    - name: Test Rasa Model
      run: rasa test

    - name: Deploy to Production (e.g., via SSH or Docker)
      run: |
        # Implement your deployment steps here
